# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98ab020e3d8d8b471a40c2fbb4a1cd927b06faf9b865115e61004548fb010377d96d755451fa09398cf947feaf57091fca2b7a5afb7c977bcc412d9cdbf07c47

test:
  secret_key_base: 8fc249f1d298f46639e368c4d6299f7e6aba10444bd659bf3c6b0e9b8741b34fb14df10a288702db8f81ae1afb15283642c5236451ff7476439960785ab15d14

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
